// This file is generated by mruby-cli. Do not touch.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <pwd.h>

/* Include the mruby header */
#include <mruby.h>
#include <mruby/array.h>

static char *mrb_get_username(mrb_state *mrb, uid_t uid)
{
  struct passwd *pw;

  if (uid < 0) {
    mrb_raise(mrb, E_RUNTIME_ERROR, "invalid uid");
  }

  pw = getpwuid(uid);

  if (pw == NULL) {
    mrb_raise(mrb, E_RUNTIME_ERROR, "getpwuid failed");
  }

  return pw->pw_name;
}

static mrb_value mrb_f_get_username(mrb_state *mrb, mrb_value self)
{
  mrb_int uid;

  mrb_get_args(mrb, "i", &uid);

  return mrb_str_new_cstr(mrb, mrb_get_username(mrb, uid));
}

static int is_symlink(char *filepath)
{
  struct stat sb = {0};
  int rc = 0;

  rc = lstat(filepath, &sb);
  if (rc < 0) {
    return -1;
  }
  if (S_ISLNK(sb.st_mode)) {
    return 1;
  }

  return 0;
}

static mrb_value mrb_read_symlink(mrb_state *mrb, char *filepath)
{
  ssize_t len = 0;
  char buf[4096] = {"\0"};
  char *path;
  int rc = 0;

  rc = is_symlink(filepath);
  if (rc != 1) {
    return mrb_str_new_lit(mrb, "");
  }
  len = readlink(filepath, buf, sizeof(buf) - 1);
  if (len < 0) {
    return mrb_false_value();
  }
  path = mrb_malloc(mrb, len + 1);
  memcpy(path, buf, len);
  path[len] = '\0';

  return mrb_str_new_cstr(mrb, path);
}

static mrb_value mrb_f_readlink(mrb_state *mrb, mrb_value self)
{
  char *path;
  mrb_value new_path;

  mrb_get_args(mrb, "z", &path);
  new_path = mrb_read_symlink(mrb, path);
  if (mrb_type(new_path) == MRB_TT_FALSE) {
    mrb_raise(mrb, E_RUNTIME_ERROR, "readlink failed");
  }

  return new_path;
}

int main(int argc, char *argv[])
{
  mrb_state *mrb = mrb_open();
  mrb_value ARGV = mrb_ary_new_capa(mrb, argc);
  int i;
  int return_value;

  for (i = 0; i < argc; i++) {
    mrb_ary_push(mrb, ARGV, mrb_str_new_cstr(mrb, argv[i]));
  }
  mrb_define_global_const(mrb, "ARGV", ARGV);

  mrb_define_method(mrb, mrb->kernel_module, "pfds_readlink", mrb_f_readlink, MRB_ARGS_REQ(1));
  mrb_define_method(mrb, mrb->kernel_module, "pfds_get_username", mrb_f_get_username, MRB_ARGS_REQ(1));

  // call __main__(ARGV)
  mrb_funcall(mrb, mrb_top_self(mrb), "__main__", 1, ARGV);

  return_value = EXIT_SUCCESS;

  if (mrb->exc) {
    mrb_print_error(mrb);
    return_value = EXIT_FAILURE;
  }
  mrb_close(mrb);

  return return_value;
}
